import Head from "next/head";
import type { NextPageWithLayout } from './_app'
import type { ReactElement } from 'react'

import Layout from '../components/layout'

import Hero1 from '../components/Hero1'

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <section>
          <Hero1 />
        </section>

      </main>

    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Page;